name: Rocket visualizer
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: rocket-data-xy
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
