name: Position XY calculation
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: rocket-data
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: rocket-data-xy
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
